import cv2

CALIB_CB_CHECKERBOARD = 0
CALIB_CB_CIRCLE_GRID_SYMMETRIC = 1
CALIB_CB_CIRCLE_GRID_ASYMMETRIC = 2

CALIB_CB_SYMMETRIC_GRID = cv2.CALIB_CB_SYMMETRIC_GRID
CALIB_CB_ASYMMETRIC_GRID = cv2.CALIB_CB_ASYMMETRIC_GRID

